/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/blaster.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.311, 1.207, -0.106]}
        rotation={[0, Math.PI / 2, 0]}
        scale={3.057}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_blasterA.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_blasterA_1.geometry}
          material={materials.dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_blasterA_2.geometry}
          material={materials.darkMetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_blasterA_3.geometry}
          material={materials.purple}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/blaster.gltf");
